# Generated by Django 4.0.6 on 2022-07-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_message_owner_room_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_description',
        ),
    ]
