# Generated by Django 4.0.6 on 2022-07-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_remove_topic_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
