# Generated by Django 4.0.6 on 2022-07-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0004_alter_topic_topic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created']},
        ),
    ]
