# Generated by Django 4.0.6 on 2022-07-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0005_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
