# Generated by Django 4.0.6 on 2022-07-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0006_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
